// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgBTyWec8BcnGkCIRdfWKfH_6yZbTLkz8',
    appId: '1:122751335450:web:9b0fbf029f55028a0825a3',
    messagingSenderId: '122751335450',
    projectId: 'survey-7f0d1',
    authDomain: 'survey-7f0d1.firebaseapp.com',
    storageBucket: 'survey-7f0d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW5YQtLUV7wLlLSTFggMP_QXtdOzNEzcs',
    appId: '1:122751335450:android:2a3dddb7db2014b20825a3',
    messagingSenderId: '122751335450',
    projectId: 'survey-7f0d1',
    storageBucket: 'survey-7f0d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh4-teNRAi4MRDn_To7JWpOMvK-0WcgrU',
    appId: '1:122751335450:ios:4def66eb0bc62c420825a3',
    messagingSenderId: '122751335450',
    projectId: 'survey-7f0d1',
    storageBucket: 'survey-7f0d1.appspot.com',
    iosBundleId: 'com.example.surveydemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh4-teNRAi4MRDn_To7JWpOMvK-0WcgrU',
    appId: '1:122751335450:ios:b7632ff0aee1c9660825a3',
    messagingSenderId: '122751335450',
    projectId: 'survey-7f0d1',
    storageBucket: 'survey-7f0d1.appspot.com',
    iosBundleId: 'com.example.surveydemo.RunnerTests',
  );
}
